# Navigation Links
main:
  - name: Home
    url: /
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Teaching
    url: teaching
    weight: 50
  - name: Contact
    url: contact
    weight: 60
